# Generated by Django 4.2.3 on 2023-08-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
